version: '2'
services:
  db:
    image: mysql:5.7.8
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: docker_development
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "4306:3306"

  web:
    tty: true
    stdin_open: true
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      # - .:/workdir
      - .:/myproject
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    links:
      - db

volumes:
  mysql-data:
  bundle: